#!/usr/bin/env bash
# Phase 9 — runs the nested-frame fuzz cases generated by
# `gen_nested.py`. Each case asserts a final domain value via its
# inline driver (Python/JS) or via an external escript driver
# (Erlang) that reads the FUZZ_EXPECTED_N comment stashed in the
# .ferl source.

set -o pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
FRAMEC=${FRAMEC:-/Users/marktruluck/projects/framepiler/target/release/framec}
CASES_DIR=$SCRIPT_DIR/cases_nested
OUT_DIR=$SCRIPT_DIR/out_nested
LOG_DIR=$SCRIPT_DIR/logs_nested
mkdir -p "$OUT_DIR" "$LOG_DIR"

LANGS=${@:-"python_3 javascript erlang"}
summary=$LOG_DIR/summary.tsv
: > "$summary"
printf "lang\tcase\tstage\tresult\terror\n" >> "$summary"

lang_to_ext() {
    case "$1" in
        python_3)   echo fpy ;;
        javascript) echo fjs ;;
        erlang)     echo ferl ;;
        *)          echo unknown ;;
    esac
}

run_one() {
    local lang=$1 case_file=$2
    local case_id
    case_id=$(basename "$case_file" | sed 's/\.f[a-z]*$//')
    local out="$OUT_DIR/$lang/$case_id"
    local errlog="$LOG_DIR/$lang-$case_id.err"
    rm -rf "$out" 2>/dev/null
    mkdir -p "$out"

    if ! "$FRAMEC" compile -l "$lang" -o "$out" "$case_file" > "$errlog" 2>&1; then
        local e
        e=$(head -3 "$errlog" | grep -v frame_runtime | tr '\n' '|' | head -c 220)
        printf "%s\t%s\ttranspile\tFAIL\t%s\n" "$lang" "$case_id" "$e" >> "$summary"
        return 1
    fi

    local gen
    gen=$(ls "$out"/*.* 2>/dev/null | head -1)
    if [ -z "$gen" ]; then
        printf "%s\t%s\ttranspile\tFAIL\tno output\n" "$lang" "$case_id" >> "$summary"
        return 1
    fi

    local result rc=0
    case "$lang" in
        python_3)
            result=$(python3 "$gen" 2>&1)
            rc=$?
            ;;
        javascript)
            local mjs="${gen%.js}.mjs"
            cp "$gen" "$mjs"
            result=$(node "$mjs" 2>&1)
            rc=$?
            ;;
        erlang)
            # Build an escript driver. The generator stashed
            # `%% FUZZ_EXPECTED_N: <int>` in the .ferl source; we
            # parse that here and assert it on the running system.
            local expected_n
            expected_n=$(grep '^%% FUZZ_EXPECTED_N:' "$case_file" | awk '{print $3}')
            local drive_arg
            drive_arg=$(grep '^%% FUZZ_DRIVE_ARG:' "$case_file" | awk '{print $3}')

            local mod
            mod=$(grep -m1 '^-module(' "$gen" | sed 's/-module(\(.*\))\./\1/')
            if [ -z "$mod" ]; then
                printf "%s\t%s\tcompile\tFAIL\tno -module\n" "$lang" "$case_id" >> "$summary"
                return 1
            fi
            local target_erl="$out/${mod}.erl"
            if [ "$gen" != "$target_erl" ]; then
                cp "$gen" "$target_erl"
            fi
            if ! (cd "$out" && erlc "$target_erl") 2>"$errlog"; then
                local e
                e=$(head -3 "$errlog" | tr '\n' '|' | head -c 220)
                printf "%s\t%s\tcompile\tFAIL\t%s\n" "$lang" "$case_id" "$e" >> "$summary"
                return 1
            fi

            # Build the escript driver. drive/0 vs drive/1 depends on
            # whether the case has a FUZZ_DRIVE_ARG line.
            local escript="$out/drive.escript"
            local drive_call
            if [ -n "$drive_arg" ]; then
                drive_call="${mod}:drive(Pid, ${drive_arg})"
            else
                drive_call="${mod}:drive(Pid)"
            fi
            cat > "$escript" << ESCRIPT
#!/usr/bin/env escript
main(_) ->
    code:add_patha("$out"),
    {ok, Pid} = ${mod}:start_link(),
    _ = ${drive_call},
    N = ${mod}:get_n(Pid),
    Expected = ${expected_n},
    case N of
        Expected -> io:format("PASS: nested-frame~n");
        Other ->
            io:format("FAIL: expected n=~p, got ~p~n", [Expected, Other]),
            halt(1)
    end.
ESCRIPT
            chmod +x "$escript"
            result=$(escript "$escript" 2>&1)
            rc=$?
            ;;
    esac

    if [ $rc -eq 0 ] && echo "$result" | grep -q "^PASS"; then
        printf "%s\t%s\trun\tPASS\t\n" "$lang" "$case_id" >> "$summary"
        return 0
    fi
    local e
    e=$(echo "$result" | head -3 | tr '\n' '|' | head -c 220)
    printf "%s\t%s\trun\tFAIL\t%s\n" "$lang" "$case_id" "$e" >> "$summary"
    return 1
}

total=0
passed=0
for lang in $LANGS; do
    ext=$(lang_to_ext "$lang")
    for case_file in "$CASES_DIR"/*."$ext"; do
        [ -f "$case_file" ] || continue
        total=$((total + 1))
        if run_one "$lang" "$case_file"; then
            passed=$((passed + 1))
        fi
    done
done

echo ""
echo "# nested-frame fuzz: $passed / $total passed"
awk -F'\t' '$4 == "FAIL" {print "  not ok " $1 "/" $2 ": " $5}' "$summary"

if [ "$passed" -ne "$total" ]; then
    exit 1
fi
exit 0
