#!/usr/bin/env bash
# Phase 9 — runs the nested-frame fuzz cases generated by
# `gen_nested.py`. Each case asserts a final domain value via its
# inline driver (Python/JS) or via an external escript driver
# (Erlang) that reads the FUZZ_EXPECTED_N comment stashed in the
# .ferl source.

set -o pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
FRAMEC=${FRAMEC:-/Users/marktruluck/projects/framepiler/target/release/framec}
CASES_DIR=$SCRIPT_DIR/cases_nested
OUT_DIR=$SCRIPT_DIR/out_nested
LOG_DIR=$SCRIPT_DIR/logs_nested
mkdir -p "$OUT_DIR" "$LOG_DIR"

LANGS=${@:-"python_3 javascript typescript ruby lua php dart rust go swift java kotlin csharp c cpp gdscript erlang"}
summary=$LOG_DIR/summary.tsv
: > "$summary"
printf "lang\tcase\tstage\tresult\terror\n" >> "$summary"

lang_to_ext() {
    case "$1" in
        python_3)   echo fpy ;;
        javascript) echo fjs ;;
        typescript) echo fts ;;
        ruby)       echo frb ;;
        lua)        echo flua ;;
        php)        echo fphp ;;
        dart)       echo fdart ;;
        rust)       echo frs ;;
        go)         echo fgo ;;
        swift)      echo fswift ;;
        java)       echo fjava ;;
        kotlin)     echo fkt ;;
        csharp)     echo fcs ;;
        c)          echo fc ;;
        cpp)        echo fcpp ;;
        gdscript)   echo fgd ;;
        erlang)     echo ferl ;;
        *)          echo unknown ;;
    esac
}

run_one() {
    local lang=$1 case_file=$2
    local case_id
    case_id=$(basename "$case_file" | sed 's/\.f[a-z]*$//')
    local out="$OUT_DIR/$lang/$case_id"
    local errlog="$LOG_DIR/$lang-$case_id.err"
    rm -rf "$out" 2>/dev/null
    mkdir -p "$out"

    if ! "$FRAMEC" compile -l "$lang" -o "$out" "$case_file" > "$errlog" 2>&1; then
        local e
        e=$(head -3 "$errlog" | grep -v frame_runtime | tr '\n' '|' | head -c 220)
        printf "%s\t%s\ttranspile\tFAIL\t%s\n" "$lang" "$case_id" "$e" >> "$summary"
        return 1
    fi

    local gen
    gen=$(ls "$out"/*.* 2>/dev/null | head -1)
    if [ -z "$gen" ]; then
        printf "%s\t%s\ttranspile\tFAIL\tno output\n" "$lang" "$case_id" >> "$summary"
        return 1
    fi

    local result rc=0
    case "$lang" in
        python_3)
            result=$(python3 "$gen" 2>&1)
            rc=$?
            ;;
        javascript)
            local mjs="${gen%.js}.mjs"
            cp "$gen" "$mjs"
            result=$(node "$mjs" 2>&1)
            rc=$?
            ;;
        typescript)
            # `tsx` runs TS sources directly without a separate compile step.
            # Allow loose typing so the runtime's `Object`-typed return slots
            # don't trip the assignment to `_n: number` — the test driver
            # already checks the value at runtime.
            result=$(tsx "$gen" 2>&1)
            rc=$?
            ;;
        ruby)
            result=$(ruby "$gen" 2>&1)
            rc=$?
            ;;
        lua)
            result=$(lua "$gen" 2>&1)
            rc=$?
            ;;
        php)
            result=$(php "$gen" 2>&1)
            rc=$?
            ;;
        dart)
            result=$(dart run "$gen" 2>&1)
            rc=$?
            ;;
        rust)
            local bin="$out/bin"
            if ! rustc -o "$bin" "$gen" 2>"$errlog"; then
                local e
                e=$(head -3 "$errlog" | tr '\n' '|' | head -c 220)
                printf "%s\t%s\tcompile\tFAIL\t%s\n" "$lang" "$case_id" "$e" >> "$summary"
                return 1
            fi
            result=$("$bin" 2>&1)
            rc=$?
            ;;
        go)
            result=$(go run "$gen" 2>&1)
            rc=$?
            ;;
        swift)
            result=$(swift "$gen" 2>&1)
            rc=$?
            ;;
        java)
            # framec emits a public class named after the @@system.
            # The test driver's `class Main` is in the same .java
            # file. javac places .class files in the same dir;
            # we run the Main class.
            local target_java="${gen%.java}.java"
            if ! (cd "$out" && javac "$target_java") 2>"$errlog"; then
                local e
                e=$(head -3 "$errlog" | tr '\n' '|' | head -c 220)
                printf "%s\t%s\tcompile\tFAIL\t%s\n" "$lang" "$case_id" "$e" >> "$summary"
                return 1
            fi
            result=$(cd "$out" && java Main 2>&1)
            rc=$?
            ;;
        kotlin)
            local jar="$out/test.jar"
            if ! kotlinc "$gen" -include-runtime -d "$jar" 2>"$errlog"; then
                local e
                e=$(head -3 "$errlog" | tr '\n' '|' | head -c 220)
                printf "%s\t%s\tcompile\tFAIL\t%s\n" "$lang" "$case_id" "$e" >> "$summary"
                return 1
            fi
            result=$(java -jar "$jar" 2>&1)
            rc=$?
            ;;
        csharp)
            # Build a single-file .NET project around the .cs file.
            # `dotnet run` requires `dotnet restore` to have produced
            # the assets file first. Run them in sequence and only
            # surface failures from the actual program execution.
            local proj_dir="$out/proj"
            mkdir -p "$proj_dir"
            cp "$gen" "$proj_dir/Program.cs"
            cat > "$proj_dir/test.csproj" << CSPROJ
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <RootNamespace>NestedFuzz</RootNamespace>
    <StartupObject>_NestedTestDriver</StartupObject>
  </PropertyGroup>
</Project>
CSPROJ
            (cd "$proj_dir" && dotnet restore -v q >"$errlog" 2>&1) || true
            result=$(cd "$proj_dir" && dotnet run -v q 2>&1)
            rc=$?
            ;;
        c)
            local bin="$out/bin"
            if ! gcc -o "$bin" "$gen" 2>"$errlog"; then
                local e
                e=$(head -3 "$errlog" | tr '\n' '|' | head -c 220)
                printf "%s\t%s\tcompile\tFAIL\t%s\n" "$lang" "$case_id" "$e" >> "$summary"
                return 1
            fi
            result=$("$bin" 2>&1)
            rc=$?
            ;;
        cpp)
            local bin="$out/bin"
            if ! g++ -std=c++17 -o "$bin" "$gen" 2>"$errlog"; then
                local e
                e=$(head -3 "$errlog" | tr '\n' '|' | head -c 220)
                printf "%s\t%s\tcompile\tFAIL\t%s\n" "$lang" "$case_id" "$e" >> "$summary"
                return 1
            fi
            result=$("$bin" 2>&1)
            rc=$?
            ;;
        gdscript)
            # Headless Godot: --script <file> --headless --quit-after 1
            # The script's `_init()` runs and `quit()` exits cleanly.
            result=$(godot --headless --script "$gen" --quit-after 1 2>&1)
            rc=$?
            ;;
        erlang)
            # Build an escript driver. The generator stashed
            # `%% FUZZ_EXPECTED_N: <int>` in the .ferl source; we
            # parse that here and assert it on the running system.
            local expected_n
            expected_n=$(grep '^%% FUZZ_EXPECTED_N:' "$case_file" | awk '{print $3}')
            local drive_arg
            drive_arg=$(grep '^%% FUZZ_DRIVE_ARG:' "$case_file" | awk '{print $3}')

            local mod
            mod=$(grep -m1 '^-module(' "$gen" | sed 's/-module(\(.*\))\./\1/')
            if [ -z "$mod" ]; then
                printf "%s\t%s\tcompile\tFAIL\tno -module\n" "$lang" "$case_id" >> "$summary"
                return 1
            fi
            local target_erl="$out/${mod}.erl"
            if [ "$gen" != "$target_erl" ]; then
                cp "$gen" "$target_erl"
            fi
            if ! (cd "$out" && erlc "$target_erl") 2>"$errlog"; then
                local e
                e=$(head -3 "$errlog" | tr '\n' '|' | head -c 220)
                printf "%s\t%s\tcompile\tFAIL\t%s\n" "$lang" "$case_id" "$e" >> "$summary"
                return 1
            fi

            # Build the escript driver. drive/0 vs drive/1 depends on
            # whether the case has a FUZZ_DRIVE_ARG line.
            local escript="$out/drive.escript"
            local drive_call
            if [ -n "$drive_arg" ]; then
                drive_call="${mod}:drive(Pid, ${drive_arg})"
            else
                drive_call="${mod}:drive(Pid)"
            fi
            cat > "$escript" << ESCRIPT
#!/usr/bin/env escript
main(_) ->
    code:add_patha("$out"),
    {ok, Pid} = ${mod}:start_link(),
    _ = ${drive_call},
    N = ${mod}:get_n(Pid),
    Expected = ${expected_n},
    case N of
        Expected -> io:format("PASS: nested-frame~n");
        Other ->
            io:format("FAIL: expected n=~p, got ~p~n", [Expected, Other]),
            halt(1)
    end.
ESCRIPT
            chmod +x "$escript"
            result=$(escript "$escript" 2>&1)
            rc=$?
            ;;
    esac

    if [ $rc -eq 0 ] && echo "$result" | grep -q "^PASS"; then
        printf "%s\t%s\trun\tPASS\t\n" "$lang" "$case_id" >> "$summary"
        return 0
    fi
    local e
    e=$(echo "$result" | head -3 | tr '\n' '|' | head -c 220)
    printf "%s\t%s\trun\tFAIL\t%s\n" "$lang" "$case_id" "$e" >> "$summary"
    return 1
}

total=0
passed=0
for lang in $LANGS; do
    ext=$(lang_to_ext "$lang")
    for case_file in "$CASES_DIR"/*."$ext"; do
        [ -f "$case_file" ] || continue
        total=$((total + 1))
        if run_one "$lang" "$case_file"; then
            passed=$((passed + 1))
        fi
    done
done

echo ""
echo "# nested-frame fuzz: $passed / $total passed"
awk -F'\t' '$4 == "FAIL" {print "  not ok " $1 "/" $2 ": " $5}' "$summary"

if [ "$passed" -ne "$total" ]; then
    exit 1
fi
exit 0
