services:
  python-runner:
    build:
      context: ./python
    volumes:
      - ../common/test-frames/v4:/tests:ro
    container_name: frame-python-runner

  typescript-runner:
    build:
      context: ./typescript
    volumes:
      - ../common/test-frames/v4:/tests:ro
    container_name: frame-typescript-runner

  rust-runner:
    build:
      context: ./rust
    volumes:
      - ../common/test-frames/v4:/tests:ro
    container_name: frame-rust-runner
