#!/usr/bin/env escript
main(_) ->
    {ok, C} = tlsclient:start_link(),
    "idle" = tlsclient:get_status(C),
    "not_ready" = tlsclient:send_app_data(C, "hello"),
    tlsclient:connect(C, "example.com"),
    "waiting server_hello" = tlsclient:get_status(C),
    "not_ready" = tlsclient:send_app_data(C, "hello"),
    tlsclient:server_hello_received(C, 772, 0, "AES-GCM"),
    "waiting ee" = tlsclient:get_status(C),
    "not_ready" = tlsclient:send_app_data(C, "hello"),
    tlsclient:encrypted_extensions_received(C),
    "waiting cert" = tlsclient:get_status(C),
    tlsclient:certificate_received(C, 1),
    "waiting cert_verify" = tlsclient:get_status(C),
    tlsclient:cert_verify_received(C, 1),
    "waiting server_finished" = tlsclient:get_status(C),
    "not_ready" = tlsclient:send_app_data(C, "hello"),
    tlsclient:server_finished_received(C, 1),
    "established" = tlsclient:get_status(C),
    "sent" = tlsclient:send_app_data(C, "hello"),
    tlsclient:close(C),
    "closed" = tlsclient:get_status(C),
    "not_ready" = tlsclient:send_app_data(C, "hello"),

    {ok, C2} = tlsclient:start_link(),
    tlsclient:connect(C2, "example.com"),
    tlsclient:server_hello_received(C2, 772, 1, "AES-GCM"),
    "aborted" = tlsclient:get_status(C2),
    "not_ready" = tlsclient:send_app_data(C2, "hello"),

    {ok, C3} = tlsclient:start_link(),
    tlsclient:connect(C3, "example.com"),
    tlsclient:server_hello_received(C3, 771, 0, "AES-GCM"),
    "aborted" = tlsclient:get_status(C3),

    {ok, C4} = tlsclient:start_link(),
    tlsclient:connect(C4, "example.com"),
    tlsclient:server_hello_received(C4, 772, 0, "RC4"),
    "aborted" = tlsclient:get_status(C4),

    {ok, C5} = tlsclient:start_link(),
    tlsclient:connect(C5, "example.com"),
    tlsclient:server_hello_received(C5, 772, 0, "AES-GCM"),
    tlsclient:encrypted_extensions_received(C5),
    tlsclient:certificate_received(C5, 0),
    "aborted" = tlsclient:get_status(C5),

    {ok, C6} = tlsclient:start_link(),
    tlsclient:connect(C6, "example.com"),
    tlsclient:server_hello_received(C6, 772, 0, "AES-GCM"),
    tlsclient:encrypted_extensions_received(C6),
    tlsclient:certificate_received(C6, 1),
    tlsclient:cert_verify_received(C6, 0),
    "aborted" = tlsclient:get_status(C6),

    {ok, C7} = tlsclient:start_link(),
    tlsclient:connect(C7, "example.com"),
    tlsclient:server_hello_received(C7, 772, 0, "AES-GCM"),
    tlsclient:encrypted_extensions_received(C7),
    tlsclient:certificate_received(C7, 1),
    tlsclient:cert_verify_received(C7, 1),
    tlsclient:server_finished_received(C7, 0),
    "aborted" = tlsclient:get_status(C7),
    "not_ready" = tlsclient:send_app_data(C7, "hello"),

    {ok, C8} = tlsclient:start_link(),
    tlsclient:connect(C8, "example.com"),
    tlsclient:timeout(C8),
    "aborted" = tlsclient:get_status(C8),

    {ok, C9} = tlsclient:start_link(),
    tlsclient:connect(C9, "example.com"),
    tlsclient:server_hello_received(C9, 772, 0, "AES-GCM"),
    tlsclient:timeout(C9),
    "aborted" = tlsclient:get_status(C9),

    io:format("PASS: tls_client~n"),
    halt(0).
