#!/usr/bin/env escript
main(_) ->
    {ok, C} = tls_client:start_link(),
    "idle" = tls_client:get_status(C),
    "not_ready" = tls_client:send_app_data(C, "hello"),
    tls_client:connect(C, "example.com"),
    "waiting server_hello" = tls_client:get_status(C),
    "not_ready" = tls_client:send_app_data(C, "hello"),
    tls_client:server_hello_received(C, 772, 0, "AES-GCM"),
    "waiting ee" = tls_client:get_status(C),
    "not_ready" = tls_client:send_app_data(C, "hello"),
    tls_client:encrypted_extensions_received(C),
    "waiting cert" = tls_client:get_status(C),
    tls_client:certificate_received(C, 1),
    "waiting cert_verify" = tls_client:get_status(C),
    tls_client:cert_verify_received(C, 1),
    "waiting server_finished" = tls_client:get_status(C),
    "not_ready" = tls_client:send_app_data(C, "hello"),
    tls_client:server_finished_received(C, 1),
    "established" = tls_client:get_status(C),
    "sent" = tls_client:send_app_data(C, "hello"),
    tls_client:close(C),
    "closed" = tls_client:get_status(C),
    "not_ready" = tls_client:send_app_data(C, "hello"),

    {ok, C2} = tls_client:start_link(),
    tls_client:connect(C2, "example.com"),
    tls_client:server_hello_received(C2, 772, 1, "AES-GCM"),
    "aborted" = tls_client:get_status(C2),
    "not_ready" = tls_client:send_app_data(C2, "hello"),

    {ok, C3} = tls_client:start_link(),
    tls_client:connect(C3, "example.com"),
    tls_client:server_hello_received(C3, 771, 0, "AES-GCM"),
    "aborted" = tls_client:get_status(C3),

    {ok, C4} = tls_client:start_link(),
    tls_client:connect(C4, "example.com"),
    tls_client:server_hello_received(C4, 772, 0, "RC4"),
    "aborted" = tls_client:get_status(C4),

    {ok, C5} = tls_client:start_link(),
    tls_client:connect(C5, "example.com"),
    tls_client:server_hello_received(C5, 772, 0, "AES-GCM"),
    tls_client:encrypted_extensions_received(C5),
    tls_client:certificate_received(C5, 0),
    "aborted" = tls_client:get_status(C5),

    {ok, C6} = tls_client:start_link(),
    tls_client:connect(C6, "example.com"),
    tls_client:server_hello_received(C6, 772, 0, "AES-GCM"),
    tls_client:encrypted_extensions_received(C6),
    tls_client:certificate_received(C6, 1),
    tls_client:cert_verify_received(C6, 0),
    "aborted" = tls_client:get_status(C6),

    {ok, C7} = tls_client:start_link(),
    tls_client:connect(C7, "example.com"),
    tls_client:server_hello_received(C7, 772, 0, "AES-GCM"),
    tls_client:encrypted_extensions_received(C7),
    tls_client:certificate_received(C7, 1),
    tls_client:cert_verify_received(C7, 1),
    tls_client:server_finished_received(C7, 0),
    "aborted" = tls_client:get_status(C7),
    "not_ready" = tls_client:send_app_data(C7, "hello"),

    {ok, C8} = tls_client:start_link(),
    tls_client:connect(C8, "example.com"),
    tls_client:timeout(C8),
    "aborted" = tls_client:get_status(C8),

    {ok, C9} = tls_client:start_link(),
    tls_client:connect(C9, "example.com"),
    tls_client:server_hello_received(C9, 772, 0, "AES-GCM"),
    tls_client:timeout(C9),
    "aborted" = tls_client:get_status(C9),

    io:format("PASS: tls_client~n"),
    halt(0).
