#!/usr/bin/env escript
main(_) ->
    {ok, F} = o_auth_pkce_flow:start_link(),
    "idle" = o_auth_pkce_flow:get_status(F),
    "no_token" = o_auth_pkce_flow:use_token(F),
    o_auth_pkce_flow:start(F, "myclient", "https://app/cb", "read", "nonce123"),
    "awaiting_redirect" = o_auth_pkce_flow:get_status(F),
    "nonce123" = o_auth_pkce_flow:get_code_verifier(F),
    "no_token" = o_auth_pkce_flow:use_token(F),
    o_auth_pkce_flow:authorization_redirect(F, "authcode-XYZ", "nonce123"),
    "exchanging" = o_auth_pkce_flow:get_status(F),
    "authcode-XYZ" = o_auth_pkce_flow:get_auth_code(F),
    o_auth_pkce_flow:exchange_response(F, "TOKEN-A", "REFRESH-B"),
    "authorized" = o_auth_pkce_flow:get_status(F),
    "TOKEN-A" = o_auth_pkce_flow:use_token(F),
    "" = o_auth_pkce_flow:get_auth_code(F),
    "" = o_auth_pkce_flow:get_code_verifier(F),
    o_auth_pkce_flow:authorization_redirect(F, "authcode-XYZ", "nonce123"),
    "authorized" = o_auth_pkce_flow:get_status(F),
    "TOKEN-A" = o_auth_pkce_flow:use_token(F),
    o_auth_pkce_flow:refresh(F),
    "refreshing" = o_auth_pkce_flow:get_status(F),
    o_auth_pkce_flow:exchange_response(F, "TOKEN-A2", "REFRESH-B2"),
    "authorized" = o_auth_pkce_flow:get_status(F),
    "TOKEN-A2" = o_auth_pkce_flow:use_token(F),
    o_auth_pkce_flow:revoke(F),
    "revoked" = o_auth_pkce_flow:get_status(F),
    "no_token" = o_auth_pkce_flow:use_token(F),

    {ok, F2} = o_auth_pkce_flow:start_link(),
    o_auth_pkce_flow:start(F2, "myclient", "https://app/cb", "read", "nonce123"),
    o_auth_pkce_flow:authorization_redirect(F2, "attacker-code", "WRONG-NONCE"),
    "failed" = o_auth_pkce_flow:get_status(F2),
    "no_token" = o_auth_pkce_flow:use_token(F2),

    {ok, F3} = o_auth_pkce_flow:start_link(),
    o_auth_pkce_flow:start(F3, "myclient", "https://app/cb", "read", "nonce123"),
    o_auth_pkce_flow:timeout(F3),
    "failed" = o_auth_pkce_flow:get_status(F3),

    {ok, F4} = o_auth_pkce_flow:start_link(),
    o_auth_pkce_flow:start(F4, "myclient", "https://app/cb", "read", "nonce123"),
    o_auth_pkce_flow:authorization_redirect(F4, "authcode", "nonce123"),
    o_auth_pkce_flow:exchange_error(F4, "invalid_grant"),
    "failed" = o_auth_pkce_flow:get_status(F4),
    "no_token" = o_auth_pkce_flow:use_token(F4),

    {ok, F5} = o_auth_pkce_flow:start_link(),
    o_auth_pkce_flow:start(F5, "myclient", "https://app/cb", "read", "nonce123"),
    o_auth_pkce_flow:authorization_redirect(F5, "authcode", "nonce123"),
    o_auth_pkce_flow:timeout(F5),
    "failed" = o_auth_pkce_flow:get_status(F5),

    {ok, F6} = o_auth_pkce_flow:start_link(),
    o_auth_pkce_flow:start(F6, "myclient", "https://app/cb", "read", "nonce123"),
    o_auth_pkce_flow:authorization_redirect(F6, "authcode", "nonce123"),
    o_auth_pkce_flow:exchange_response(F6, "TOKEN", "REFRESH"),
    o_auth_pkce_flow:refresh(F6),
    o_auth_pkce_flow:exchange_error(F6, "invalid_refresh_token"),
    "failed" = o_auth_pkce_flow:get_status(F6),

    io:format("PASS: oauth_pkce~n"),
    halt(0).
