#!/usr/bin/env escript
main(_) ->
    {ok, F} = oauthpkceflow:start_link(),
    "idle" = oauthpkceflow:get_status(F),
    "no_token" = oauthpkceflow:use_token(F),
    oauthpkceflow:start(F, "myclient", "https://app/cb", "read", "nonce123"),
    "awaiting_redirect" = oauthpkceflow:get_status(F),
    "nonce123" = oauthpkceflow:get_code_verifier(F),
    "no_token" = oauthpkceflow:use_token(F),
    oauthpkceflow:authorization_redirect(F, "authcode-XYZ", "nonce123"),
    "exchanging" = oauthpkceflow:get_status(F),
    "authcode-XYZ" = oauthpkceflow:get_auth_code(F),
    oauthpkceflow:exchange_response(F, "TOKEN-A", "REFRESH-B"),
    "authorized" = oauthpkceflow:get_status(F),
    "TOKEN-A" = oauthpkceflow:use_token(F),
    "" = oauthpkceflow:get_auth_code(F),
    "" = oauthpkceflow:get_code_verifier(F),
    oauthpkceflow:authorization_redirect(F, "authcode-XYZ", "nonce123"),
    "authorized" = oauthpkceflow:get_status(F),
    "TOKEN-A" = oauthpkceflow:use_token(F),
    oauthpkceflow:refresh(F),
    "refreshing" = oauthpkceflow:get_status(F),
    oauthpkceflow:exchange_response(F, "TOKEN-A2", "REFRESH-B2"),
    "authorized" = oauthpkceflow:get_status(F),
    "TOKEN-A2" = oauthpkceflow:use_token(F),
    oauthpkceflow:revoke(F),
    "revoked" = oauthpkceflow:get_status(F),
    "no_token" = oauthpkceflow:use_token(F),

    {ok, F2} = oauthpkceflow:start_link(),
    oauthpkceflow:start(F2, "myclient", "https://app/cb", "read", "nonce123"),
    oauthpkceflow:authorization_redirect(F2, "attacker-code", "WRONG-NONCE"),
    "failed" = oauthpkceflow:get_status(F2),
    "no_token" = oauthpkceflow:use_token(F2),

    {ok, F3} = oauthpkceflow:start_link(),
    oauthpkceflow:start(F3, "myclient", "https://app/cb", "read", "nonce123"),
    oauthpkceflow:timeout(F3),
    "failed" = oauthpkceflow:get_status(F3),

    {ok, F4} = oauthpkceflow:start_link(),
    oauthpkceflow:start(F4, "myclient", "https://app/cb", "read", "nonce123"),
    oauthpkceflow:authorization_redirect(F4, "authcode", "nonce123"),
    oauthpkceflow:exchange_error(F4, "invalid_grant"),
    "failed" = oauthpkceflow:get_status(F4),
    "no_token" = oauthpkceflow:use_token(F4),

    {ok, F5} = oauthpkceflow:start_link(),
    oauthpkceflow:start(F5, "myclient", "https://app/cb", "read", "nonce123"),
    oauthpkceflow:authorization_redirect(F5, "authcode", "nonce123"),
    oauthpkceflow:timeout(F5),
    "failed" = oauthpkceflow:get_status(F5),

    {ok, F6} = oauthpkceflow:start_link(),
    oauthpkceflow:start(F6, "myclient", "https://app/cb", "read", "nonce123"),
    oauthpkceflow:authorization_redirect(F6, "authcode", "nonce123"),
    oauthpkceflow:exchange_response(F6, "TOKEN", "REFRESH"),
    oauthpkceflow:refresh(F6),
    oauthpkceflow:exchange_error(F6, "invalid_refresh_token"),
    "failed" = oauthpkceflow:get_status(F6),

    io:format("PASS: oauth_pkce~n"),
    halt(0).
