#!/usr/bin/env escript
main(_) ->
    {ok, M} = mfaauth:start_link(),
    "idle" = mfaauth:get_status(M),
    mfaauth:submit_second_factor(M, "123456"),
    "idle" = mfaauth:get_status(M),
    mfaauth:submit_username(M, "alice"),
    "awaiting_password" = mfaauth:get_status(M),
    mfaauth:submit_second_factor(M, "123456"),
    "awaiting_password" = mfaauth:get_status(M),
    mfaauth:submit_password(M, "hunter2"),
    "awaiting_2fa" = mfaauth:get_status(M),
    0 = mfaauth:get_failures(M),
    mfaauth:submit_second_factor(M, "123456"),
    "authenticated" = mfaauth:get_status(M),
    0 = mfaauth:get_failures(M),
    mfaauth:logout(M),
    "idle" = mfaauth:get_status(M),

    {ok, M2} = mfaauth:start_link(),
    mfaauth:submit_username(M2, "alice"),
    mfaauth:submit_password(M2, "wrong"),
    1 = mfaauth:get_failures(M2),
    "awaiting_password" = mfaauth:get_status(M2),
    mfaauth:submit_password(M2, "wrong"),
    mfaauth:submit_password(M2, "wrong"),
    mfaauth:submit_password(M2, "wrong"),
    4 = mfaauth:get_failures(M2),
    mfaauth:submit_password(M2, "wrong"),
    "locked" = mfaauth:get_status(M2),
    5 = mfaauth:get_failures(M2),
    mfaauth:submit_username(M2, "alice"),
    mfaauth:submit_password(M2, "hunter2"),
    mfaauth:submit_second_factor(M2, "123456"),
    "locked" = mfaauth:get_status(M2),
    mfaauth:cooldown_elapsed(M2),
    "idle" = mfaauth:get_status(M2),
    4 = mfaauth:get_failures(M2),

    {ok, M3} = mfaauth:start_link(),
    mfaauth:submit_username(M3, "alice"),
    mfaauth:submit_password(M3, "hunter2"),
    "awaiting_2fa" = mfaauth:get_status(M3),
    mfaauth:submit_second_factor(M3, "bad1"),
    "awaiting_2fa" = mfaauth:get_status(M3),
    mfaauth:submit_second_factor(M3, "bad2"),
    mfaauth:submit_second_factor(M3, "bad3"),
    "awaiting_password" = mfaauth:get_status(M3),
    1 = mfaauth:get_failures(M3),
    mfaauth:submit_password(M3, "hunter2"),
    mfaauth:submit_second_factor(M3, "bad"),
    "awaiting_2fa" = mfaauth:get_status(M3),

    io:format("PASS: mfa_lockout~n"),
    halt(0).
