#!/usr/bin/env escript
main(_) ->
    {ok, K} = kerberosclient:start_link(),
    "idle" = kerberosclient:get_status(K),
    kerberosclient:request_service(K, "HTTP/web"),
    "idle" = kerberosclient:get_status(K),
    "" = kerberosclient:get_service_ticket(K),
    kerberosclient:authenticate(K, "alice", "pw"),
    "awaiting_tgt" = kerberosclient:get_status(K),
    kerberosclient:request_service(K, "HTTP/web"),
    "awaiting_tgt" = kerberosclient:get_status(K),
    kerberosclient:preauth_accepted(K, "TGT-abc", "K-123", 100),
    "has_tgt" = kerberosclient:get_status(K),
    "TGT-abc" = kerberosclient:get_tgt(K),
    kerberosclient:tick(K, 50),
    "has_tgt" = kerberosclient:get_status(K),
    kerberosclient:request_service(K, "HTTP/web"),
    "awaiting_st" = kerberosclient:get_status(K),
    kerberosclient:service_ticket_received(K, "ST-xyz", 80),
    "has_st" = kerberosclient:get_status(K),
    "ST-xyz" = kerberosclient:get_service_ticket(K),
    kerberosclient:tick(K, 85),
    "has_tgt" = kerberosclient:get_status(K),
    "" = kerberosclient:get_service_ticket(K),
    "TGT-abc" = kerberosclient:get_tgt(K),
    kerberosclient:request_service(K, "HTTP/web"),
    kerberosclient:service_ticket_received(K, "ST-2", 95),
    "has_st" = kerberosclient:get_status(K),
    kerberosclient:tick(K, 100),
    "idle" = kerberosclient:get_status(K),
    "" = kerberosclient:get_tgt(K),
    "" = kerberosclient:get_service_ticket(K),

    {ok, K2} = kerberosclient:start_link(),
    kerberosclient:authenticate(K2, "alice", "pw"),
    kerberosclient:preauth_accepted(K2, "TGT-xx", "K-yy", 200),
    kerberosclient:logout(K2),
    "idle" = kerberosclient:get_status(K2),
    "" = kerberosclient:get_tgt(K2),

    {ok, K3} = kerberosclient:start_link(),
    kerberosclient:authenticate(K3, "alice", "pw"),
    kerberosclient:preauth_accepted(K3, "TGT-1", "K-1", 500),
    kerberosclient:request_service(K3, "spn"),
    kerberosclient:service_ticket_received(K3, "ST-1", 300),
    kerberosclient:logout(K3),
    "idle" = kerberosclient:get_status(K3),
    "" = kerberosclient:get_service_ticket(K3),

    {ok, K4} = kerberosclient:start_link(),
    kerberosclient:authenticate(K4, "bob", "wrong"),
    kerberosclient:preauth_rejected(K4, "invalid_password"),
    "failed" = kerberosclient:get_status(K4),

    {ok, K5} = kerberosclient:start_link(),
    kerberosclient:authenticate(K5, "alice", "pw"),
    kerberosclient:preauth_accepted(K5, "TGT-q", "K-q", 500),
    kerberosclient:request_service(K5, "deny_me"),
    kerberosclient:service_ticket_rejected(K5, "no_access"),
    "has_tgt" = kerberosclient:get_status(K5),
    "TGT-q" = kerberosclient:get_tgt(K5),

    io:format("PASS: kerberos~n"),
    halt(0).
