#!/usr/bin/env escript
main(_) ->
    {ok, N} = noisexxinitiator:start_link(),
    "idle" = noisexxinitiator:get_status(N),
    "not_ready" = noisexxinitiator:send(N, "hi"),
    "" = noisexxinitiator:recv(N, "ct"),
    noisexxinitiator:msg2_received(N, 1),
    "idle" = noisexxinitiator:get_status(N),
    noisexxinitiator:msg3_ack(N),
    "idle" = noisexxinitiator:get_status(N),
    noisexxinitiator:start(N, "peer"),
    "awaiting_msg2" = noisexxinitiator:get_status(N),
    "not_ready" = noisexxinitiator:send(N, "hi"),
    noisexxinitiator:msg3_ack(N),
    "awaiting_msg2" = noisexxinitiator:get_status(N),
    noisexxinitiator:msg2_received(N, 1),
    "awaiting_ack" = noisexxinitiator:get_status(N),
    "not_ready" = noisexxinitiator:send(N, "hi"),
    noisexxinitiator:msg2_received(N, 1),
    "awaiting_ack" = noisexxinitiator:get_status(N),
    noisexxinitiator:msg3_ack(N),
    "transport" = noisexxinitiator:get_status(N),
    "sent" = noisexxinitiator:send(N, "hi"),
    "decrypted" = noisexxinitiator:recv(N, "ct"),

    {ok, N2} = noisexxinitiator:start_link(),
    noisexxinitiator:start(N2, "peer"),
    noisexxinitiator:msg2_received(N2, 0),
    "aborted" = noisexxinitiator:get_status(N2),
    "not_ready" = noisexxinitiator:send(N2, "hi"),
    "" = noisexxinitiator:recv(N2, "ct"),

    {ok, N3} = noisexxinitiator:start_link(),
    noisexxinitiator:start(N3, "peer"),
    noisexxinitiator:timeout(N3),
    "aborted" = noisexxinitiator:get_status(N3),

    {ok, N4} = noisexxinitiator:start_link(),
    noisexxinitiator:start(N4, "peer"),
    noisexxinitiator:msg2_received(N4, 1),
    noisexxinitiator:timeout(N4),
    "aborted" = noisexxinitiator:get_status(N4),
    noisexxinitiator:start(N4, "peer"),
    noisexxinitiator:msg2_received(N4, 1),
    noisexxinitiator:msg3_ack(N4),
    "aborted" = noisexxinitiator:get_status(N4),

    io:format("PASS: noise_xx~n"),
    halt(0).
