#!/usr/bin/env escript
main(_) ->
    {ok, N} = noise_xx_initiator:start_link(),
    "idle" = noise_xx_initiator:get_status(N),
    "not_ready" = noise_xx_initiator:send(N, "hi"),
    "" = noise_xx_initiator:recv(N, "ct"),
    noise_xx_initiator:msg2_received(N, 1),
    "idle" = noise_xx_initiator:get_status(N),
    noise_xx_initiator:msg3_ack(N),
    "idle" = noise_xx_initiator:get_status(N),
    noise_xx_initiator:start(N, "peer"),
    "awaiting_msg2" = noise_xx_initiator:get_status(N),
    "not_ready" = noise_xx_initiator:send(N, "hi"),
    noise_xx_initiator:msg3_ack(N),
    "awaiting_msg2" = noise_xx_initiator:get_status(N),
    noise_xx_initiator:msg2_received(N, 1),
    "awaiting_ack" = noise_xx_initiator:get_status(N),
    "not_ready" = noise_xx_initiator:send(N, "hi"),
    noise_xx_initiator:msg2_received(N, 1),
    "awaiting_ack" = noise_xx_initiator:get_status(N),
    noise_xx_initiator:msg3_ack(N),
    "transport" = noise_xx_initiator:get_status(N),
    "sent" = noise_xx_initiator:send(N, "hi"),
    "decrypted" = noise_xx_initiator:recv(N, "ct"),

    {ok, N2} = noise_xx_initiator:start_link(),
    noise_xx_initiator:start(N2, "peer"),
    noise_xx_initiator:msg2_received(N2, 0),
    "aborted" = noise_xx_initiator:get_status(N2),
    "not_ready" = noise_xx_initiator:send(N2, "hi"),
    "" = noise_xx_initiator:recv(N2, "ct"),

    {ok, N3} = noise_xx_initiator:start_link(),
    noise_xx_initiator:start(N3, "peer"),
    noise_xx_initiator:timeout(N3),
    "aborted" = noise_xx_initiator:get_status(N3),

    {ok, N4} = noise_xx_initiator:start_link(),
    noise_xx_initiator:start(N4, "peer"),
    noise_xx_initiator:msg2_received(N4, 1),
    noise_xx_initiator:timeout(N4),
    "aborted" = noise_xx_initiator:get_status(N4),
    noise_xx_initiator:start(N4, "peer"),
    noise_xx_initiator:msg2_received(N4, 1),
    noise_xx_initiator:msg3_ack(N4),
    "aborted" = noise_xx_initiator:get_status(N4),

    io:format("PASS: noise_xx~n"),
    halt(0).
