#!/usr/bin/env escript
main(_) ->
    {ok, S} = doubleratchetsession:start_link(),
    "uninit" = doubleratchetsession:get_status(S),
    "" = doubleratchetsession:send_plaintext(S, "hi"),
    "" = doubleratchetsession:receive_ciphertext(S, "h", "ct", 0, 1),
    doubleratchetsession:initialize(S, "root-secret", "remote-pub"),
    "active" = doubleratchetsession:get_status(S),
    "ct-send" = doubleratchetsession:send_plaintext(S, "m1"),
    "ct-send" = doubleratchetsession:send_plaintext(S, "m2"),
    2 = doubleratchetsession:get_sends(S),
    Sends = doubleratchetsession:get_sends(S),
    Sends = doubleratchetsession:get_zeroized(S),
    "pt" = doubleratchetsession:receive_ciphertext(S, "h1", "c1", 0, 1),
    1 = doubleratchetsession:get_recvs(S),
    0 = doubleratchetsession:get_ratchets(S),
    "pt" = doubleratchetsession:receive_ciphertext(S, "h2", "c2", 1, 1),
    1 = doubleratchetsession:get_ratchets(S),
    2 = doubleratchetsession:get_recvs(S),
    Total = doubleratchetsession:get_sends(S) + doubleratchetsession:get_recvs(S),
    Total = doubleratchetsession:get_zeroized(S),
    BeforeRecvs = doubleratchetsession:get_recvs(S),
    BeforeZeroized = doubleratchetsession:get_zeroized(S),
    "decryption_failed" = doubleratchetsession:receive_ciphertext(S, "bad", "bad", 0, 0),
    BeforeRecvs = doubleratchetsession:get_recvs(S),
    BeforeZeroized = doubleratchetsession:get_zeroized(S),
    doubleratchetsession:close(S),
    "closed" = doubleratchetsession:get_status(S),
    "" = doubleratchetsession:send_plaintext(S, "hi"),
    "" = doubleratchetsession:receive_ciphertext(S, "h", "ct", 0, 1),
    io:format("PASS: double_ratchet~n"),
    halt(0).
