#!/usr/bin/env escript
main(_) ->
    {ok, S} = zerotrustsession:start_link(),
    "anonymous" = zerotrustsession:get_status(S),
    "denied" = zerotrustsession:request_resource(S, "doc", "ch1", 1),
    zerotrustsession:authenticate(S, "alice", "dev-1", "ch-A", "totp"),
    "authenticating" = zerotrustsession:get_status(S),
    "denied" = zerotrustsession:request_resource(S, "doc", "ch-A", 1),
    zerotrustsession:auth_result(S, 1, 30),
    "full_access" = zerotrustsession:get_status(S),
    30 = zerotrustsession:get_risk(S),
    "allowed" = zerotrustsession:request_resource(S, "doc", "ch-A", 1),
    "denied_policy" = zerotrustsession:request_resource(S, "doc", "ch-A", 0),
    zerotrustsession:channel_binding_mismatch(S),
    "terminated" = zerotrustsession:get_status(S),
    "denied" = zerotrustsession:request_resource(S, "doc", "ch-A", 1),

    {ok, S2} = zerotrustsession:start_link(),
    zerotrustsession:authenticate(S2, "bob", "dev-2", "ch-B", "totp"),
    zerotrustsession:auth_result(S2, 1, 20),
    "denied_channel" = zerotrustsession:request_resource(S2, "doc", "ch-WRONG", 1),
    "terminated" = zerotrustsession:get_status(S2),

    {ok, S3} = zerotrustsession:start_link(),
    zerotrustsession:authenticate(S3, "carol", "dev-3", "ch-C", "totp"),
    zerotrustsession:auth_result(S3, 1, 85),
    "step_up_required" = zerotrustsession:get_status(S3),
    "denied_stepup" = zerotrustsession:request_resource(S3, "doc", "ch-C", 1),
    zerotrustsession:authenticate(S3, "carol", "dev-3", "ch-C", "u2f"),
    "authenticating" = zerotrustsession:get_status(S3),
    zerotrustsession:auth_result(S3, 1, 30),
    "full_access" = zerotrustsession:get_status(S3),

    {ok, S4} = zerotrustsession:start_link(),
    zerotrustsession:authenticate(S4, "dave", "dev-4", "ch-D", "totp"),
    zerotrustsession:auth_result(S4, 1, 20),
    zerotrustsession:posture_update(S4, 50),
    "degraded" = zerotrustsession:get_status(S4),
    "allowed_low_trust" = zerotrustsession:request_resource(S4, "doc", "ch-D", 1),
    "denied_low_trust" = zerotrustsession:request_resource(S4, "doc", "ch-D", 0),
    zerotrustsession:posture_update(S4, 80),
    "full_access" = zerotrustsession:get_status(S4),
    zerotrustsession:risk_signal_update(S4, 95),
    "terminated" = zerotrustsession:get_status(S4),

    {ok, S5} = zerotrustsession:start_link(),
    zerotrustsession:authenticate(S5, "eve", "dev-5", "ch-E", "totp"),
    zerotrustsession:auth_result(S5, 1, 20),
    zerotrustsession:risk_signal_update(S5, 75),
    "degraded" = zerotrustsession:get_status(S5),

    {ok, S6} = zerotrustsession:start_link(),
    zerotrustsession:authenticate(S6, "fred", "dev-6", "ch-F", "totp"),
    zerotrustsession:auth_result(S6, 1, 20),
    zerotrustsession:logout(S6),
    "anonymous" = zerotrustsession:get_status(S6),

    {ok, S7} = zerotrustsession:start_link(),
    zerotrustsession:authenticate(S7, "greg", "dev-7", "ch-G", "totp"),
    zerotrustsession:auth_result(S7, 1, 20),
    zerotrustsession:session_heartbeat(S7),
    "full_access" = zerotrustsession:get_status(S7),

    io:format("PASS: zero_trust~n"),
    halt(0).
