#!/usr/bin/env escript
main(_) ->
    {ok, R} = delivery_robot:start_link(),
    "idle" = delivery_robot:status(R),
    delivery_robot:deliver(R, 1, 5),
    "approaching" = delivery_robot:status(R),
    1 = delivery_robot:pickup_floor(R),
    5 = delivery_robot:drop_floor(R),
    delivery_robot:boarded(R),
    "approaching" = delivery_robot:status(R),
    delivery_robot:exited(R),
    "approaching" = delivery_robot:status(R),
    delivery_robot:at_elevator(R),
    "boarding" = delivery_robot:status(R),
    delivery_robot:boarded(R),
    "riding" = delivery_robot:status(R),
    delivery_robot:at_destination_floor(R),
    "exiting" = delivery_robot:status(R),
    delivery_robot:exited(R),
    "dropping" = delivery_robot:status(R),
    delivery_robot:dropped_off(R),
    "idle" = delivery_robot:status(R),
    delivery_robot:deliver(R, 5, 1),
    5 = delivery_robot:pickup_floor(R),
    1 = delivery_robot:drop_floor(R),
    {ok, R2} = delivery_robot:start_link(),
    delivery_robot:at_elevator(R2),
    delivery_robot:boarded(R2),
    delivery_robot:dropped_off(R2),
    "idle" = delivery_robot:status(R2),
    io:format("PASS: delivery_robot~n"),
    halt(0).
