#!/usr/bin/env escript
main(_) ->
    {ok, P} = pick_place:start_link(),
    pick_place:start_task(P, 1.0, 2.0),
    "scanning" = pick_place:status(P),
    pick_place:vision_result(P, 1),
    "planning_grasp" = pick_place:status(P),
    pick_place:grasp_plan_ready(P),
    "approaching" = pick_place:status(P),
    pick_place:at_waypoint(P),
    "grasping" = pick_place:status(P),
    pick_place:gripper_closed(P),
    "lifting" = pick_place:status(P),
    pick_place:at_waypoint(P),
    "moving_to_place" = pick_place:status(P),
    pick_place:at_waypoint(P),
    "placing" = pick_place:status(P),
    pick_place:gripper_released(P),
    "idle" = pick_place:status(P),

    {ok, P2} = pick_place:start_link(),
    pick_place:start_task(P2, 1.0, 2.0),
    pick_place:vision_result(P2, 0),
    "scanning" = pick_place:status(P2),
    2 = pick_place:get_vision_retries(P2),
    pick_place:vision_result(P2, 0),
    pick_place:vision_result(P2, 0),
    "failed" = pick_place:status(P2),

    {ok, P3} = pick_place:start_link(),
    pick_place:start_task(P3, 1.0, 2.0),
    pick_place:vision_result(P3, 1),
    pick_place:grasp_plan_failed(P3),
    "planning_grasp" = pick_place:status(P3),
    2 = pick_place:get_grasp_retries(P3),
    pick_place:grasp_plan_failed(P3),
    "scanning" = pick_place:status(P3),
    0 = pick_place:get_grasp_retries(P3),

    {ok, P4} = pick_place:start_link(),
    pick_place:start_task(P4, 1.0, 2.0),
    pick_place:vision_result(P4, 1),
    pick_place:grasp_plan_ready(P4),
    pick_place:at_waypoint(P4),
    pick_place:gripper_closed(P4),
    pick_place:slip_detected(P4),
    "scanning" = pick_place:status(P4),

    {ok, P5} = pick_place:start_link(),
    pick_place:start_task(P5, 1.0, 2.0),
    pick_place:vision_result(P5, 1),
    pick_place:abort(P5),
    "aborted" = pick_place:status(P5),

    pick_place:start_task(P5, 3.0, 4.0),
    "scanning" = pick_place:status(P5),

    io:format("PASS: pick_place~n"),
    halt(0).
