#!/usr/bin/env escript
main(_) ->
    {ok, R} = fleet_robot:start_link(["bot-1"]),
    "available" = fleet_robot:state_name(R),
    "bot-1" = fleet_robot:id(R),
    "" = fleet_robot:current_task_id(R),
    fleet_robot:task_complete(R),
    fleet_robot:task_failed(R),
    "available" = fleet_robot:state_name(R),
    fleet_robot:assign_task(R, "task-42"),
    "busy" = fleet_robot:state_name(R),
    "task-42" = fleet_robot:current_task_id(R),
    fleet_robot:assign_task(R, "task-99"),
    "busy" = fleet_robot:state_name(R),
    "task-42" = fleet_robot:current_task_id(R),
    fleet_robot:tick(R), fleet_robot:tick(R),
    "busy" = fleet_robot:state_name(R),
    fleet_robot:tick(R), fleet_robot:tick(R), fleet_robot:tick(R),
    "available" = fleet_robot:state_name(R),
    "" = fleet_robot:current_task_id(R),
    fleet_robot:assign_task(R, "task-43"),
    fleet_robot:task_complete(R),
    "available" = fleet_robot:state_name(R),
    fleet_robot:assign_task(R, "task-44"),
    fleet_robot:task_failed(R),
    "available" = fleet_robot:state_name(R),
    {ok, R2} = fleet_robot:start_link(["bot-2"]),
    "bot-2" = fleet_robot:id(R2),
    "available" = fleet_robot:state_name(R2),
    fleet_robot:assign_task(R, "t1"), fleet_robot:task_complete(R),
    fleet_robot:assign_task(R, "t2"), fleet_robot:task_complete(R),
    fleet_robot:assign_task(R, "t3"), fleet_robot:task_complete(R),
    "available" = fleet_robot:state_name(R),
    io:format("PASS: fleet_robot~n"),
    halt(0).
