#!/bin/bash
# Batched Rust test runner.
#   1. Transpile every .frs to /rust_runner/src/bin/<sanitized>.rs.
#      Cargo auto-detects each as a bin target.
#   2. ONE `cargo build --release` builds all bins in parallel — deps
#      (serde/tokio) are compiled once, not once per test.
#   3. Iterate: exec target/release/<sanitized>, capture output, emit TAP.
#
# On compile failure: scrape error lines, attribute to bins, remove,
# retry once. If the retry still fails, mark all remaining RUN tests as
# COMPILE_FAIL.

set -uo pipefail

# Source-hash cache for framec: skips re-transpile when source
# + framec version haven't changed since last run.
. /framec_cached.sh

OUTPUT="/output"
PROJECT="/rust_runner"
BIN_SRC="${PROJECT}/src/bin"
BIN_DIR="${PROJECT}/target/release"
MANIFEST="/tmp/rust_manifest.tsv"
COMPILE_ONLY="${COMPILE_ONLY:-false}"

target="rust"
ext="frs"

mkdir -p "$OUTPUT"
rm -rf "$BIN_SRC" "$MANIFEST" 2>/dev/null
mkdir -p "$BIN_SRC"
: > "$MANIFEST"

# Delete the stock src/main.rs so cargo doesn't try to build a useless
# default binary. It's regenerated by the Dockerfile's `cargo init` and
# contains only `println!("Hello, world!");`.
rm -f "${PROJECT}/src/main.rs" 2>/dev/null

tests=$(find /tests/common/positive -name "*.$ext" 2>/dev/null | sort)
lang_tests=$(find /tests/rust -name "*.$ext" 2>/dev/null | sort)
if [ -n "$lang_tests" ]; then
    tests="$tests
$lang_tests"
fi

test_count=$(echo "$tests" | grep -c . || echo 0)
if [ "$test_count" -eq 0 ]; then
    echo "TAP version 14"
    echo "1..0 # SKIP no rust tests found"
    exit 0
fi

echo "TAP version 14"
echo "1..$test_count"

test_num=0

for test_file in $tests; do
    test_num=$((test_num + 1))
    test_name=$(basename "$test_file" ".$ext")

    if head -10 "$test_file" 2>/dev/null | grep -qE "@@skip|@skip"; then
        printf '%s\tSKIP\t%s\n' "$test_num" "$test_name" >> "$MANIFEST"
        continue
    fi

    sanitized=$(printf '%s' "$test_name" | sed 's/[^A-Za-z0-9_]/_/g')
    # Prefix with test_num so duplicate basenames (e.g. two
    # forward_parent tests in different categories) get unique ids.
    sanitized="t${test_num}_${sanitized}"
    bin_src="$BIN_SRC/${sanitized}.rs"

    # framec emits <test_name>.rs to -o dir. Use a temp dir then copy to
    # sanitized filename under src/bin/.
    tmp_dir=$(mktemp -d)
    if ! framec_cached "$target" "$tmp_dir" "$test_file" /tmp/compile_err; then
        rm -rf "$tmp_dir"
        if echo "$test_file" | grep -q "transpile-error"; then
            printf '%s\tTRANSPILE_ERROR_OK\t%s\n' "$test_num" "$test_name" >> "$MANIFEST"
        else
            err_line=$(head -5 /tmp/compile_err 2>/dev/null | tr '\n' '\\' | sed 's/\\$//' | sed 's/\\/\\n/g')
            printf '%s\tTRANSPILE_FAIL\t%s\t\t%s\n' "$test_num" "$test_name" "$err_line" >> "$MANIFEST"
        fi
        continue
    fi
    src=$(ls "$tmp_dir"/*.rs 2>/dev/null | head -1)
    if [ -z "$src" ]; then
        rm -rf "$tmp_dir"
        printf '%s\tNO_OUTPUT\t%s\n' "$test_num" "$test_name" >> "$MANIFEST"
        continue
    fi
    mv "$src" "$bin_src"
    rm -rf "$tmp_dir"

    if [ "$COMPILE_ONLY" = "true" ]; then
        printf '%s\tCOMPILE_ONLY\t%s\n' "$test_num" "$test_name" >> "$MANIFEST"
        continue
    fi

    printf '%s\tRUN\t%s\t%s\n' "$test_num" "$test_name" "$sanitized" >> "$MANIFEST"
done

if [ "$COMPILE_ONLY" = "true" ]; then
    pass=0; fail=0; skip=0
    while IFS=$'\t' read -r num status name rest; do
        case "$status" in
            SKIP)                   echo "ok $num - $name # SKIP";                              skip=$((skip+1)) ;;
            TRANSPILE_ERROR_OK)     echo "ok $num - $name # correctly rejected by transpiler";  pass=$((pass+1)) ;;
            TRANSPILE_FAIL)         echo "not ok $num - $name # transpile failed";              fail=$((fail+1)) ;;
            NO_OUTPUT)              echo "not ok $num - $name # no output file";                fail=$((fail+1)) ;;
            COMPILE_ONLY|RUN)       echo "ok $num - $name # transpiled";                        pass=$((pass+1)) ;;
        esac
    done < "$MANIFEST"
    echo ""
    echo "# rust: $pass passed, $fail failed, $skip skipped"
    exit $fail
fi

try_build() {
    ( cd "$PROJECT" && cargo build --release 2>&1 ) > /tmp/cargo_build.log
    return "${PIPESTATUS[0]:-$?}"
}

# cargo exits non-zero on any compile error. Scrape error messages to
# attribute failures to specific bins, remove them, retry once.
# --message-format=short gives `file:line:col: error: message` one-line
# format — much easier to scrape than the rustc default.
cd "$PROJECT"
cargo build --release --message-format=short >/tmp/cargo_build.log 2>&1
build_status=$?

if [ $build_status -ne 0 ]; then
    # Filter to error lines only (skip warnings), then extract bin names.
    bad=$(grep -E ":[[:space:]]+error" /tmp/cargo_build.log \
            | grep -oE "src/bin/[A-Za-z0-9_]+\.rs" \
            | sed 's|src/bin/||;s|\.rs$||' | sort -u)
    if [ -n "$bad" ]; then
        for s in $bad; do
            tmp_manifest="${MANIFEST}.tmp"
            awk -v s="$s" -F'\t' 'BEGIN{OFS="\t"} {
                if ($2 == "RUN" && $4 == s) { $2 = "COMPILE_FAIL"; $4 = "" }
                print
            }' "$MANIFEST" > "$tmp_manifest"
            mv "$tmp_manifest" "$MANIFEST"
            rm -f "$BIN_SRC/${s}.rs"
        done
        cargo build --release --message-format=short >/tmp/cargo_build.log 2>&1
        build_status=$?
    fi
fi

if [ $build_status -ne 0 ]; then
    tmp_manifest="${MANIFEST}.tmp"
    awk -F'\t' 'BEGIN{OFS="\t"} {
        if ($2 == "RUN") { $2 = "COMPILE_FAIL"; $4 = "" }
        print
    }' "$MANIFEST" > "$tmp_manifest"
    mv "$tmp_manifest" "$MANIFEST"
    echo "# cargo build failed even after removing bad bins — see below" >&2
    tail -40 /tmp/cargo_build.log >&2
fi

# Execute each test binary in parallel. Per-test timeout via `timeout`.
# stdout+stderr captured to per-test files to avoid bash subshell quoting
# issues and enable parallel execution without output interleaving.
TIMEOUT_SEC="${RUST_TEST_TIMEOUT:-30}"
JOBS="${RUST_EXEC_JOBS:-$(nproc 2>/dev/null || echo 4)}"
EXEC_DIR="/tmp/rust_exec_status"
rm -rf "$EXEC_DIR" 2>/dev/null
mkdir -p "$EXEC_DIR"
export EXEC_DIR BIN_DIR TIMEOUT_SEC

exec_one() {
    local sanitized="$1"
    local bin_path="$BIN_DIR/$sanitized"
    if [ ! -x "$bin_path" ]; then
        echo 127 > "$EXEC_DIR/${sanitized}.rc"
        echo "binary missing" > "$EXEC_DIR/${sanitized}.out"
        return
    fi
    timeout "$TIMEOUT_SEC" "$bin_path" > "$EXEC_DIR/${sanitized}.out" 2>&1
    echo $? > "$EXEC_DIR/${sanitized}.rc"
}
export -f exec_one

awk -F'\t' '$2 == "RUN" { print $4 }' "$MANIFEST" | \
    xargs -n 1 -P "$JOBS" -I{} bash -c 'exec_one "$@"' _ {}

pass=0; fail=0; skip=0
while IFS=$'\t' read -r num status name rest; do
    IFS=$'\t' read -r bin extra <<< "$rest"
    bin="${bin:-}"
    case "$status" in
        SKIP)
            echo "ok $num - $name # SKIP"; skip=$((skip+1)) ;;
        TRANSPILE_ERROR_OK)
            echo "ok $num - $name # correctly rejected by transpiler"; pass=$((pass+1)) ;;
        TRANSPILE_FAIL)
            echo "not ok $num - $name # transpile failed"; fail=$((fail+1)) ;;
        NO_OUTPUT)
            echo "not ok $num - $name # no output file"; fail=$((fail+1)) ;;
        COMPILE_FAIL)
            echo "not ok $num - $name # cargo build failed"; fail=$((fail+1)) ;;
        RUN)
            rc_file="$EXEC_DIR/${bin}.rc"
            out_file="$EXEC_DIR/${bin}.out"
            if [ ! -f "$rc_file" ]; then
                echo "not ok $num - $name # not executed"; fail=$((fail+1)); continue
            fi
            code=$(cat "$rc_file")
            out=$(cat "$out_file" 2>/dev/null)
            if [ "$code" = "124" ]; then
                echo "not ok $num - $name # TIMEOUT"; fail=$((fail+1))
            elif [ "$code" != "0" ]; then
                echo "not ok $num - $name # runtime error (exit $code)"
                echo "$out" | head -5 | sed 's/^/  # /'
                fail=$((fail+1))
            elif echo "$out" | grep -q "^not ok "; then
                echo "not ok $num - $name"; fail=$((fail+1))
            elif echo "$out" | grep -qE "^ok |PASS"; then
                echo "ok $num - $name"; pass=$((pass+1))
            elif [ -z "$out" ]; then
                echo "ok $num - $name # clean exit"; pass=$((pass+1))
            else
                echo "not ok $num - $name # unrecognized output"
                echo "$out" | head -3 | sed 's/^/  # /'
                fail=$((fail+1))
            fi ;;
        *)
            echo "not ok $num - $name # unknown status $status"; fail=$((fail+1)) ;;
    esac
done < "$MANIFEST"

# Integrity check — pass+fail+skip must equal declared plan count. Catches
# silent dispatcher crashes / missing rows in the manifest.
if [ "$((pass + fail + skip))" -ne "$test_count" ]; then
    echo "not ok $((test_count + 1)) - __harness_integrity__ # expected $test_count results, got $((pass + fail + skip))"
    fail=$((fail + 1))
fi


echo ""
echo "# rust: $pass passed, $fail failed, $skip skipped"
exit $fail
