#!/usr/bin/env escript
main(_) ->
    {ok, W} = substance:start_link(0.0, 100.0, 10000.0),
    "solid" = substance:phase(W),
    substance:add_heat(W, 209.0),
    "melting" = substance:phase(W),
    substance:add_heat(W, 334.0),
    "liquid" = substance:phase(W),
    substance:add_heat(W, 418.0),
    "boiling" = substance:phase(W),
    substance:add_heat(W, 2260.0),
    "gas" = substance:phase(W),
    substance:add_heat(W, 41382.0),
    "plasma" = substance:phase(W),
    substance:remove_heat(W, 1.0),
    "gas" = substance:phase(W),
    substance:remove_heat(W, 41400.0),
    "boiling" = substance:phase(W),
    substance:remove_heat(W, 2260.0),
    "liquid" = substance:phase(W),
    substance:remove_heat(W, 418.0),
    "melting" = substance:phase(W),
    substance:remove_heat(W, 334.0),
    "solid" = substance:phase(W),
    io:format("PASS: phases_of_matter~n"),
    halt(0).
