#!/usr/bin/env escript
main(_) ->
    {ok, N} = neuron:start_link(),
    "resting" = neuron:phase(N),
    -70.0 = neuron:voltage(N),
    neuron:stimulate(N, 5.0),
    "resting" = neuron:phase(N),
    -65.0 = neuron:voltage(N),
    neuron:stimulate(N, 5.0),
    "resting" = neuron:phase(N),
    neuron:stimulate(N, 6.0),
    "spike" = neuron:phase(N),
    40.0 = neuron:voltage(N),
    neuron:tick(N),
    "repolarizing" = neuron:phase(N),
    neuron:tick(N),
    "refractory" = neuron:phase(N),
    -80.0 = neuron:voltage(N),
    neuron:stimulate(N, 100.0),
    "refractory" = neuron:phase(N),
    -80.0 = neuron:voltage(N),
    neuron:tick(N),
    "refractory" = neuron:phase(N),
    neuron:tick(N),
    "refractory" = neuron:phase(N),
    neuron:tick(N),
    "resting" = neuron:phase(N),
    neuron:stimulate(N, 30.0),
    "spike" = neuron:phase(N),
    io:format("PASS: neuron_action~n"),
    halt(0).
