#!/usr/bin/env escript
main(_) ->
    {ok, T} = titration:start_link(),
    "setup" = titration:status(T),
    titration:add_drop(T, 1.0),
    "titrating" = titration:status(T),
    0.0 = titration:volume_mL(T),
    titration:add_drop(T, 5.0),
    titration:add_drop(T, 3.0),
    8.0 = titration:volume_mL(T),
    titration:observe_color(T, "pink"),
    "near endpoint" = titration:status(T),
    titration:observe_color(T, "clear"),
    "titrating" = titration:status(T),
    titration:observe_color(T, "pink"),
    "near endpoint" = titration:status(T),
    titration:add_drop(T, 0.05),
    titration:record_endpoint(T),
    "complete" = titration:status(T),
    true = abs(titration:result_mL(T) - 8.05) < 1.0e-9,
    titration:add_drop(T, 10.0),
    true = abs(titration:result_mL(T) - 8.05) < 1.0e-9,
    titration:add_drop(T, 5.0),
    true = abs(titration:result_mL(T) - 8.05) < 1.0e-9,
    titration:observe_color(T, "pink"),
    titration:record_endpoint(T),
    true = abs(titration:result_mL(T) - 8.05) < 1.0e-9,
    titration:new_trial(T),
    "setup" = titration:status(T),
    0.0 = titration:volume_mL(T),
    titration:add_drop(T, 2.0),
    titration:add_drop(T, 1.5),
    titration:observe_color(T, "pink"),
    titration:record_endpoint(T),
    true = abs(titration:result_mL(T) - 1.5) < 1.0e-9,
    io:format("PASS: titration~n"),
    halt(0).
