#!/usr/bin/env escript
main(_) ->
    {ok, P} = pcrcycler:start_link(3),
    "idle" = pcrcycler:phase(P),
    25.0 = pcrcycler:temperature(P),
    0 = pcrcycler:current_cycle(P),
    pcrcycler:tick_minute(P),
    "idle" = pcrcycler:phase(P),
    pcrcycler:start(P),
    "denature" = pcrcycler:phase(P),
    1 = pcrcycler:current_cycle(P),
    95.0 = pcrcycler:temperature(P),
    pcrcycler:tick_minute(P),
    "anneal" = pcrcycler:phase(P),
    55.0 = pcrcycler:temperature(P),
    pcrcycler:tick_minute(P),
    "extend" = pcrcycler:phase(P),
    72.0 = pcrcycler:temperature(P),
    pcrcycler:tick_minute(P),
    "extend" = pcrcycler:phase(P),
    pcrcycler:tick_minute(P),
    "denature" = pcrcycler:phase(P),
    2 = pcrcycler:current_cycle(P),
    pcrcycler:tick_minute(P), "anneal" = pcrcycler:phase(P),
    pcrcycler:tick_minute(P), "extend" = pcrcycler:phase(P),
    pcrcycler:tick_minute(P), pcrcycler:tick_minute(P),
    "denature" = pcrcycler:phase(P),
    3 = pcrcycler:current_cycle(P),
    pcrcycler:tick_minute(P), pcrcycler:tick_minute(P), pcrcycler:tick_minute(P),
    pcrcycler:tick_minute(P),
    "final hold" = pcrcycler:phase(P),
    4.0 = pcrcycler:temperature(P),
    pcrcycler:tick_minute(P),
    "final hold" = pcrcycler:phase(P),
    pcrcycler:start(P),
    "final hold" = pcrcycler:phase(P),
    io:format("PASS: pcr_cycler~n"),
    halt(0).
