#!/usr/bin/env escript
main(_) ->
    {ok, P} = infusion_pump:start_link(),
    "off" = infusion_pump:status(P),
    infusion_pump:set_rate(P, 100.0),
    0.0 = infusion_pump:rate_mL_per_hr(P),
    infusion_pump:start_infusion(P),
    "off" = infusion_pump:status(P),
    infusion_pump:power_on(P),
    "idle" = infusion_pump:status(P),
    infusion_pump:set_rate(P, 100.0),
    100.0 = infusion_pump:rate_mL_per_hr(P),
    infusion_pump:start_infusion(P),
    "idle" = infusion_pump:status(P),
    0.0 = infusion_pump:volume_delivered(P),
    infusion_pump:prime(P),
    "primed" = infusion_pump:status(P),
    infusion_pump:start_infusion(P),
    "running" = infusion_pump:status(P),
    tick_n(P, 10),
    "running" = infusion_pump:status(P),
    VolAfter10 = infusion_pump:volume_delivered(P),
    true = abs(VolAfter10 - (10.0 * 100.0 / 60.0)) < 1.0e-9,
    infusion_pump:occlusion_detected(P),
    "alarm" = infusion_pump:status(P),
    "occlusion" = infusion_pump:alarm_reason(P),
    infusion_pump:start_infusion(P),
    infusion_pump:prime(P),
    infusion_pump:tick_minute(P),
    "alarm" = infusion_pump:status(P),
    true = abs(infusion_pump:volume_delivered(P) - VolAfter10) < 1.0e-9,
    infusion_pump:acknowledge_alarm(P),
    "idle" = infusion_pump:status(P),
    100.0 = infusion_pump:rate_mL_per_hr(P),
    infusion_pump:prime(P),
    infusion_pump:start_infusion(P),
    infusion_pump:tick_minute(P),
    true = abs(infusion_pump:volume_delivered(P) - (VolAfter10 + 100.0/60.0)) < 1.0e-9,
    io:format("PASS: infusion_pump~n"),
    halt(0).

tick_n(_P, 0) -> ok;
tick_n(P, N) ->
    infusion_pump:tick_minute(P),
    tick_n(P, N - 1).
