#!/usr/bin/env escript
main(_) ->
    {ok, P} = infusionpump:start_link(),
    "off" = infusionpump:status(P),
    infusionpump:set_rate(P, 100.0),
    0.0 = infusionpump:rate_mL_per_hr(P),
    infusionpump:start_infusion(P),
    "off" = infusionpump:status(P),
    infusionpump:power_on(P),
    "idle" = infusionpump:status(P),
    infusionpump:set_rate(P, 100.0),
    100.0 = infusionpump:rate_mL_per_hr(P),
    infusionpump:start_infusion(P),
    "idle" = infusionpump:status(P),
    0.0 = infusionpump:volume_delivered(P),
    infusionpump:prime(P),
    "primed" = infusionpump:status(P),
    infusionpump:start_infusion(P),
    "running" = infusionpump:status(P),
    tick_n(P, 10),
    "running" = infusionpump:status(P),
    VolAfter10 = infusionpump:volume_delivered(P),
    true = abs(VolAfter10 - (10.0 * 100.0 / 60.0)) < 1.0e-9,
    infusionpump:occlusion_detected(P),
    "alarm" = infusionpump:status(P),
    "occlusion" = infusionpump:alarm_reason(P),
    infusionpump:start_infusion(P),
    infusionpump:prime(P),
    infusionpump:tick_minute(P),
    "alarm" = infusionpump:status(P),
    true = abs(infusionpump:volume_delivered(P) - VolAfter10) < 1.0e-9,
    infusionpump:acknowledge_alarm(P),
    "idle" = infusionpump:status(P),
    100.0 = infusionpump:rate_mL_per_hr(P),
    infusionpump:prime(P),
    infusionpump:start_infusion(P),
    infusionpump:tick_minute(P),
    true = abs(infusionpump:volume_delivered(P) - (VolAfter10 + 100.0/60.0)) < 1.0e-9,
    io:format("PASS: infusion_pump~n"),
    halt(0).

tick_n(_P, 0) -> ok;
tick_n(P, N) ->
    infusionpump:tick_minute(P),
    tick_n(P, N - 1).
