#!/usr/bin/env escript
main(_) ->
    {ok, V} = ventilator:start_link(),
    "off" = ventilator:phase(V),
    ventilator:power_on(V),
    "inspiration" = ventilator:phase(V),
    1 = ventilator:breath_count(V),
    ventilator:patient_effort_detected(V),
    "inspiration" = ventilator:phase(V),
    ventilator:tick_ms(V, 500),
    "inspiration" = ventilator:phase(V),
    ventilator:tick_ms(V, 500),
    "expiration" = ventilator:phase(V),
    ventilator:patient_effort_detected(V),
    "expiration" = ventilator:phase(V),
    ventilator:tick_ms(V, 1500),
    "pause" = ventilator:phase(V),
    ventilator:patient_effort_detected(V),
    "inspiration" = ventilator:phase(V),
    2 = ventilator:breath_count(V),
    ventilator:tick_ms(V, 1000),
    "expiration" = ventilator:phase(V),
    ventilator:tick_ms(V, 1500),
    "pause" = ventilator:phase(V),
    ventilator:tick_ms(V, 500),
    "inspiration" = ventilator:phase(V),
    3 = ventilator:breath_count(V),
    ventilator:stop(V),
    "off" = ventilator:phase(V),
    3 = ventilator:breath_count(V),
    ventilator:tick_ms(V, 10000),
    ventilator:patient_effort_detected(V),
    "off" = ventilator:phase(V),
    io:format("PASS: ventilator~n"),
    halt(0).
