#!/usr/bin/env escript
main(_) ->
    {ok, A} = aed:start_link(),
    "off" = aed:status(A),
    aed:press_shock(A),
    0 = aed:shock_count(A),
    aed:power_on(A),
    "attach pads" = aed:status(A),
    aed:press_shock(A),
    0 = aed:shock_count(A),
    aed:pads_attached(A),
    "analyzing" = aed:status(A),
    aed:press_shock(A),
    0 = aed:shock_count(A),
    aed:rhythm_detected(A, "VF"),
    "charging" = aed:status(A),
    aed:press_shock(A),
    0 = aed:shock_count(A),
    aed:tick_ms(A, 50),
    "charging" = aed:status(A),
    50 = aed:charge_pct(A),
    aed:press_shock(A),
    0 = aed:shock_count(A),
    aed:tick_ms(A, 50),
    "awaiting clear" = aed:status(A),
    aed:press_shock(A),
    0 = aed:shock_count(A),
    aed:confirm_clear(A),
    "ready to shock" = aed:status(A),
    aed:press_shock(A),
    1 = aed:shock_count(A),
    "analyzing" = aed:status(A),
    aed:rhythm_detected(A, "asystole"),
    "no shock advised" = aed:status(A),
    aed:press_shock(A),
    aed:tick_ms(A, 100),
    aed:confirm_clear(A),
    "no shock advised" = aed:status(A),
    1 = aed:shock_count(A),
    io:format("PASS: aed~n"),
    halt(0).
