#!/usr/bin/env escript
main(_) ->
    {ok, A} = a_e_d:start_link(),
    "off" = a_e_d:status(A),
    a_e_d:press_shock(A),
    0 = a_e_d:shock_count(A),
    a_e_d:power_on(A),
    "attach pads" = a_e_d:status(A),
    a_e_d:press_shock(A),
    0 = a_e_d:shock_count(A),
    a_e_d:pads_attached(A),
    "analyzing" = a_e_d:status(A),
    a_e_d:press_shock(A),
    0 = a_e_d:shock_count(A),
    a_e_d:rhythm_detected(A, "VF"),
    "charging" = a_e_d:status(A),
    a_e_d:press_shock(A),
    0 = a_e_d:shock_count(A),
    a_e_d:tick_ms(A, 50),
    "charging" = a_e_d:status(A),
    50 = a_e_d:charge_pct(A),
    a_e_d:press_shock(A),
    0 = a_e_d:shock_count(A),
    a_e_d:tick_ms(A, 50),
    "awaiting clear" = a_e_d:status(A),
    a_e_d:press_shock(A),
    0 = a_e_d:shock_count(A),
    a_e_d:confirm_clear(A),
    "ready to shock" = a_e_d:status(A),
    a_e_d:press_shock(A),
    1 = a_e_d:shock_count(A),
    "analyzing" = a_e_d:status(A),
    a_e_d:rhythm_detected(A, "asystole"),
    "no shock advised" = a_e_d:status(A),
    a_e_d:press_shock(A),
    a_e_d:tick_ms(A, 100),
    a_e_d:confirm_clear(A),
    "no shock advised" = a_e_d:status(A),
    1 = a_e_d:shock_count(A),
    io:format("PASS: aed~n"),
    halt(0).
