#!/usr/bin/env escript
main(_) ->
    {ok, C} = acls:start_link(),
    "pre-arrest" = acls:phase(C),
    acls:rhythm_check(C, "VF"),
    acls:cpr_cycle_complete(C),
    acls:rosc_achieved(C),
    "pre-arrest" = acls:phase(C),
    acls:start_code(C),
    "analyzing" = acls:phase(C),
    acls:rhythm_check(C, "VF"),
    "cpr shockable" = acls:phase(C),
    1 = acls:shocks_given(C),
    acls:give_epinephrine(C),
    "cpr shockable" = acls:phase(C),
    acls:cpr_cycle_complete(C),
    "analyzing" = acls:phase(C),
    1 = acls:cpr_cycles_done(C),
    acls:rhythm_check(C, "asystole"),
    "cpr non-shockable" = acls:phase(C),
    1 = acls:shocks_given(C),
    acls:cpr_cycle_complete(C),
    2 = acls:cpr_cycles_done(C),
    acls:rhythm_check(C, "pulseless_VT"),
    "cpr shockable" = acls:phase(C),
    2 = acls:shocks_given(C),
    acls:rosc_achieved(C),
    "rosc" = acls:phase(C),
    acls:rhythm_check(C, "VF"),
    acls:cpr_cycle_complete(C),
    acls:rosc_achieved(C),
    "rosc" = acls:phase(C),
    2 = acls:shocks_given(C),

    {ok, C2} = acls:start_link(),
    acls:start_code(C2),
    acls:rhythm_check(C2, "asystole"),
    acls:pronounce(C2),
    "terminated" = acls:phase(C2),
    acls:rosc_achieved(C2),
    acls:rhythm_check(C2, "VF"),
    "terminated" = acls:phase(C2),
    io:format("PASS: acls~n"),
    halt(0).
