#!/usr/bin/env escript
main(_) ->
    {ok, C} = a_c_l_s:start_link(),
    "pre-arrest" = a_c_l_s:phase(C),
    a_c_l_s:rhythm_check(C, "VF"),
    a_c_l_s:cpr_cycle_complete(C),
    a_c_l_s:rosc_achieved(C),
    "pre-arrest" = a_c_l_s:phase(C),
    a_c_l_s:start_code(C),
    "analyzing" = a_c_l_s:phase(C),
    a_c_l_s:rhythm_check(C, "VF"),
    "cpr shockable" = a_c_l_s:phase(C),
    1 = a_c_l_s:shocks_given(C),
    a_c_l_s:give_epinephrine(C),
    "cpr shockable" = a_c_l_s:phase(C),
    a_c_l_s:cpr_cycle_complete(C),
    "analyzing" = a_c_l_s:phase(C),
    1 = a_c_l_s:cpr_cycles_done(C),
    a_c_l_s:rhythm_check(C, "asystole"),
    "cpr non-shockable" = a_c_l_s:phase(C),
    1 = a_c_l_s:shocks_given(C),
    a_c_l_s:cpr_cycle_complete(C),
    2 = a_c_l_s:cpr_cycles_done(C),
    a_c_l_s:rhythm_check(C, "pulseless_VT"),
    "cpr shockable" = a_c_l_s:phase(C),
    2 = a_c_l_s:shocks_given(C),
    a_c_l_s:rosc_achieved(C),
    "rosc" = a_c_l_s:phase(C),
    a_c_l_s:rhythm_check(C, "VF"),
    a_c_l_s:cpr_cycle_complete(C),
    a_c_l_s:rosc_achieved(C),
    "rosc" = a_c_l_s:phase(C),
    2 = a_c_l_s:shocks_given(C),

    {ok, C2} = a_c_l_s:start_link(),
    a_c_l_s:start_code(C2),
    a_c_l_s:rhythm_check(C2, "asystole"),
    a_c_l_s:pronounce(C2),
    "terminated" = a_c_l_s:phase(C2),
    a_c_l_s:rosc_achieved(C2),
    a_c_l_s:rhythm_check(C2, "VF"),
    "terminated" = a_c_l_s:phase(C2),
    io:format("PASS: acls~n"),
    halt(0).
